### PR TITLE
Made option parsing more robust by switching to CommandLineParser

### PR DESCRIPTION
**Pull request by rodcloutier**
I propose to use [CommandLineParser](http://commandline.codeplex.com/) to parse our options
This will make parsing more robust.

### CODE REVIEW

**Comment by jelmansouri** [comment]
Last time I checked I had an issue with premake and NuGet packages, they were not working properly on vs2015 gen. Which IDE are you using?

**Comment by rodcloutier** [comment]
I  am using vs2015 and  they do have some issues with the premake5 gen. What I did is that  
I generated the solution,  uninstalled the nuget package, removed the packages solution dir and finally reinstalled the package...

**Comment by rodcloutier** [comment]
I have tried several versions of the generator and the support for nuget is broken everywhere. How would you propose to handle this? Should we leave it in the premake file and document the procedure to actuall y install it? Should we just document that you need to do a Nuget install from within VisualStudio?

**Comment by jelmansouri** [comment]
Hmm, looked at the premake-nuget generation code and it seems to have been done for vs2010 and not touched since. I think we should just drop it from sharpmake and add documentation steps on how to add the packages.
I'll open a ticket with premake on the meantime.
(FYI, we are working on open sourcing sharpmake, and I'll probably move all this to sharpmake)

**Comment by rodcloutier** [comment]
Fine. I will do that.

**Pull request merged**
